### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by Creatium** [bd808/php-unserialize-js#22]
Hello,

Would it be possible to add Typescript type declarations in the near future?

**Comment by bd808** [comment]
@Creatium does #23 do what you need?

**Comment by Creatium** [comment]
Hello,

Yes, I think that will be it!

**Comment by volfadar** [comment]
![image](https://github.com/bd808/php-unserialize-js/assets/44869940/ab8a2a29-95aa-4922-94dc-f311ab411fd6)

hi @bd808, i think you forgot to add `default` in the ts definition. because in the js it is exported as default function, and it is actually only works if i didn't do object destructuring the module. sorry for my bad english.

![image](https://github.com/bd808/php-unserialize-js/assets/44869940/4fb43df3-b33a-4c69-a5a4-e759681a5617)
