### ISSUE TITLE
Can I use this within a classic ASP page?

### ISSUE THREAD

**Issue by johnbcable** [bd808/php-unserialize-js#7]
I have a classic ASP page that has no HTML content. For normal Javascript, I would save the JS with a  .asp extension and then use a server-side include to bring the functions in. This does not work with phpUnserialize.js

I need to deal with data from a remote MySQL database that has been saved in one or more columns with the PHP serialize() function and all I want to return is JSON to my clients.

Thanks for your help

**Comment by bd808** [comment]
I haven't used classic ASP since it was just called ASP (NT 4.5 ~1999). You may need to figure out what a classic ASP adapter for [Universal Module Definition](https://github.com/umdjs/umd) looks like. I'd be glad to take a small patch that makes use from classic ASP easier as long as it doesn't break other UMD consumers.
