### ISSUE TITLE
Parser does't support binary strings

### ISSUE THREAD

**Issue by uglide** [bd808/php-unserialize-js#9]
Serialized objects can containt null bytes. From [php.net](http://php.net/manual/en/function.serialize.php):

> Object's private members have the class name prepended to the member name; protected members 
> have a '\*' prepended to the member name. These **prepended values have null bytes on either side**.

**Comment by bd808** [comment]
That quote is about protected member names in the serialization of an object. That is supported; see https://github.com/bd808/php-unserialize-js/blob/master/phpUnserialize.js#L164-L206

Serialized strings could also contain embedded nulls and the parser should deal with that fine as well because PHP string serialization is done by sending a length and the data: https://github.com/bd808/php-unserialize-js/blob/master/phpUnserialize.js#L79-L98

Do  you have an example of valid PHP serialized data that is failing to parse for you?

**Comment by uglide** [comment]
@bd808 Thanks for the response!
